In [1]:
import numpy as np

In [5]:
np.array([1, 2], dtype=float)

array([1., 2.])

In [6]:
import scipy

In [19]:
a = np.array([1, 2, 4])
b = np.array([3, 1, 1])

In [22]:
len(b)

3

In [20]:
scipy.spatial.distance.cdist(b, a, metric='euclidean')

ValueError: XA must be a 2-dimensional array.

In [11]:
from scipy import spatial

In [24]:
scipy.spatial.distance.cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean')

array([[3.74165739]])

In [26]:
scipy.spatial.distance.cdist(a[:, np.newaxis], b[:, np.newaxis], metric='euclidean')

array([[2., 0., 0.],
       [1., 1., 1.],
       [1., 3., 3.]])

In [27]:
?scipy.spatial.distance.cdist

In [33]:
a[:, np.newaxis]

array([[1],
       [2],
       [4]])

In [32]:
a[np.newaxis, :]

array([[1, 2, 4]])

In [29]:
a * b

array([3, 2, 4])

In [30]:
np.dot(a, b)

9

In [31]:
a.dot(b)

9

In [34]:
np.arange(1, 2, 0.3, dtype=float)

array([1. , 1.3, 1.6, 1.9])

In [35]:
(5, 1)

(5, 1)

In [36]:
type((5, 1))

tuple

In [38]:
a.reshape((3, 1))

array([[1],
       [2],
       [4]])