# Задача 1: сравнение предложений

In [1]:
import codecs

In [22]:
file = codecs.open('sentences.txt')

In [23]:
lines = file.readlines()

In [24]:
len(lines)

22

In [25]:
lines = [s.lower() for s in lines]

In [26]:
len(lines)

22

In [83]:
l = lines[2]

In [84]:
l

'a common interactive use of cat for a single file is to output the content of a file to standard output.\n'

In [34]:
import re

In [49]:
all_words = dict()
for l in lines:
    tokens = re.split('[^a-z]', l)
    tokens = [t for t in tokens if len(t) != 0]
    for t in tokens:
        if not all_words.has_key(t):
            all_words[t] = len(all_words)

In [50]:
all_words

{'a': 33,
 'according': 167,
 'adjacent': 114,
 'allow': 185,
 'allows': 196,
 'also': 24,
 'an': 230,
 'ancestor': 77,
 'and': 58,
 'animals': 61,
 'any': 152,
 'app': 208,
 'apple': 168,
 'are': 78,
 'arguments': 153,
 'artificial': 66,
 'as': 14,
 'available': 164,
 'based': 200,
 'basic': 136,
 'be': 23,
 'between': 95,
 'binary': 27,
 'both': 79,
 'by': 56,
 'bytes': 20,
 'can': 22,
 'cat': 15,
 'catenates': 17,
 'cats': 4,
 'changes': 9,
 'chromosomes': 84,
 'clear': 130,
 'closest': 75,
 'command': 135,
 'commands': 125,
 'common': 34,
 'community': 193,
 'comparison': 1,
 'computers': 178,
 'concatenate': 26,
 'concern': 107,
 'connected': 127,
 'contains': 169,
 'content': 42,
 'count': 253,
 'create': 242,
 'default': 109,
 'delete': 119,
 'deliberately': 64,
 'developed': 194,
 'diploid': 80,
 'disk': 244,
 'displays': 155,
 'dogs': 3,
 'domestic': 87,
 'domesticated': 73,
 'domestication': 12,
 'download': 205,
 'drive': 248,
 'during': 10,
 'ears': 52,
 'editions': 166,
 '

In [51]:
import numpy as np

In [55]:
len(all_words)

254

In [77]:
m = np.zeros((len(lines), len(all_words)), dtype=int)
m.shape

(22, 254)

In [78]:
for l_i, l in enumerate(lines):
    tokens = re.split('[^a-z]', l)
    tokens = [t for t in tokens if len(t) != 0]
    for t in tokens:
        t_i = all_words[t]
        m[l_i][t_i] += 1

In [79]:
m

array([[1, 1, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 2, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 1, 1]])

In [82]:
for t, n in all_words.iteritems():
    if n == 2:
        print(t)

to


In [85]:
m.shape

(22, 254)

In [86]:
import scipy

In [89]:
from scipy import spatial

In [102]:
from sortedcontainers import SortedList

In [162]:
dist = SortedList()
for row_i, row in enumerate(m):
    cos = scipy.spatial.distance.cosine(m[0], row)
    print row_i, ' : ', cos
    dist.add((cos, row_i))
dist

0  :  0.0
1  :  0.9527544408738466
2  :  0.8644738145642124
3  :  0.8951715163278082
4  :  0.7770887149698589
5  :  0.9402385695332803
6  :  0.7327387580875756
7  :  0.9258750683338899
8  :  0.8842724875284311
9  :  0.9055088817476932
10  :  0.8328165362273942
11  :  0.8804771390665607
12  :  0.8396432548525454
13  :  0.8703592552895671
14  :  0.8740118423302576
15  :  0.9442721787424647
16  :  0.8406361854220809
17  :  0.956644501523794
18  :  0.9442721787424647
19  :  0.8885443574849294
20  :  0.8427572744917122
21  :  0.8250364469440588


SortedList([(0.0, 0), (0.7327387580875756, 6), (0.7770887149698589, 4), (0.8250364469440588, 21), (0.8328165362273942, 10), (0.8396432548525454, 12), (0.8406361854220809, 16), (0.8427572744917122, 20), (0.8644738145642124, 2), (0.8703592552895671, 13), (0.8740118423302576, 14), (0.8804771390665607, 11), (0.8842724875284311, 8), (0.8885443574849294, 19), (0.8951715163278082, 3), (0.9055088817476932, 9), (0.9258750683338899, 7), (0.9402385695332803, 5), (0.9442721787424647, 15), (0.9442721787424647, 18), (0.9527544408738466, 1), (0.956644501523794, 17)])

In [107]:
lines[0]

'in comparison to dogs, cats have not undergone major changes during the domestication process.\n'

In [156]:
lines[6]

'domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).\n'

In [168]:
m[0]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [169]:
m[6]

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [175]:
def equal_words(line_i):
    return [i for i, x in enumerate(m[0]) if x != 0 and m[line_i][i] != 0]

In [184]:
word_i_to_word = dict()
for w, i in all_words.iteritems():
    word_i_to_word[i] = w
word_i_to_word

{0: 'in',
 1: 'comparison',
 2: 'to',
 3: 'dogs',
 4: 'cats',
 5: 'have',
 6: 'not',
 7: 'undergone',
 8: 'major',
 9: 'changes',
 10: 'during',
 11: 'the',
 12: 'domestication',
 13: 'process',
 14: 'as',
 15: 'cat',
 16: 'simply',
 17: 'catenates',
 18: 'streams',
 19: 'of',
 20: 'bytes',
 21: 'it',
 22: 'can',
 23: 'be',
 24: 'also',
 25: 'used',
 26: 'concatenate',
 27: 'binary',
 28: 'files',
 29: 'where',
 30: 'will',
 31: 'just',
 32: 'sequence',
 33: 'a',
 34: 'common',
 35: 'interactive',
 36: 'use',
 37: 'for',
 38: 'single',
 39: 'file',
 40: 'is',
 41: 'output',
 42: 'content',
 43: 'standard',
 44: 'hear',
 45: 'sounds',
 46: 'too',
 47: 'faint',
 48: 'or',
 49: 'high',
 50: 'frequency',
 51: 'human',
 52: 'ears',
 53: 'such',
 54: 'those',
 55: 'made',
 56: 'by',
 57: 'mice',
 58: 'and',
 59: 'other',
 60: 'small',
 61: 'animals',
 62: 'one',
 63: 'people',
 64: 'deliberately',
 65: 'tamed',
 66: 'artificial',
 67: 'selection',
 68: 'they',
 69: 'were',
 70: 'useful',
 71

In [186]:
def print_equal_words(line_i):
    for w_i in equal_words(line_i):
        print word_i_to_word[w_i]

In [191]:
print_equal_words(10)

in
the
